services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookshop_api
    env_file:
      - .env
    volumes:
      - ./public:/app/public
    ports:
      - "3001:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      maildev:
        condition: service_started
    restart: always
    command: sh -c "npx prisma migrate deploy && node dist/index.js"

  postgres:
    image: postgres:16
    container_name: postgres_book
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: bookshop
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d bookshop"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_book
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:7
    container_name: redis_local
    ports:
      - "6379:6379"
    restart: always

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: always

volumes:
  postgres_data:
